<?php
/**
 * @file
 *
 * Installation of the carrotomics module
 */


/**
 * Implements hook_requirements().
 */
function carrotomics_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!module_exists('tripal_core') and !module_exists('tripal')) {
      $requirements['carrotomics-tripal'] = [
        'title' => "carrotomics",
        'value' => "ERROR: You must have Tripal v2 or v3 installed to use this module.",
        'severity' => REQUIREMENT_ERROR,
      ];
    }
    // Make sure chado is installed.
    if (!$GLOBALS["chado_is_installed"]) {
      $requirements['carrotomics-chado'] = [
        'title' => "carrotomics",
        'value' => "ERROR: Chado is not installed. Version 1.3 must be installed before this module can be enabled",
        'severity' => REQUIREMENT_ERROR,
      ];
    }
    // Requires chado version 1.3
    else {
      $chado_version = chado_get_version();
      if ($chado_version < '1.3') {
        $requirements['carrotomics-chado'] = [
          'title' => "carrotomics",
          'value' => "ERROR: Chado version is $chado_version, this module requires version 1.3",
          'severity' => REQUIREMENT_ERROR,
        ];
      }
    }
  }
  return $requirements;
}

/**
 * Implements hook_install().
 *
 * Performs actions when the module is first installed.
 *
 * @ingroup carrotomics
 */
function carrotomics_install() {
  // Add custom tables
  carrotomics_add_custom_tables();
  // Add columns to chado.nd_geolocation table
  carrotomics_update_nd_geolocation();
  // Add various required cv terms
  carrotomics_add_cv_terms();
}

/**
 * Implements hook_uninstall().
 *
 * Performs actions when the module is uninstalled.
 * Warning: data in new custom table columns will be lost!
 *
 * @ingroup carrotomics
 */
function carrotomics_uninstall() {
  db_drop_field('chado.nd_geolocation', 'latitude_dev');
  db_drop_field('chado.nd_geolocation', 'longitude_dev');
  db_drop_field('chado.nd_geolocation', 'altitude_dev');
  db_drop_table('chado.stock_analysis');
  db_drop_table('chado.project_featuremap');
}

/**
 * Add custom stock_analysis table
 */
function carrotomics_add_table_stock_analysis() {
  $schema = [
    'fields' => [
      'stock_analysis_id' => ['type' => 'serial', 'not null' => TRUE],
      'stock_id' => ['type' => 'int', 'not null' => TRUE],
      'analysis_id' => ['type' => 'int', 'not null' => TRUE],
    ],
    'primary key' => ['stock_analysis_id'],
    'foreign keys' => [
      'stock' => [
        'table' => 'stock',
        'columns' => [
          'stock_id' => 'stock_id',
        ],
      ],
      'analysis' => [
        'table' => 'analysis',
        'columns' => [
          'analysis_id' => 'analysis_id',
        ],
      ],
    ],
    'indexes' => [
      'stock_analysis_idx1' => ['stock_id'],
      'stock_analysis_idx2' => ['analysis_id'],
    ],
    'unique keys' => [
      'stock_analysis_unique_uq1' => ['stock_id', 'analysis_id'],
    ],
  ];
  chado_create_custom_table('stock_analysis', $schema, TRUE, NULL, FALSE);
}

/**
 * Add custom project_featuremap table
 */
function carrotomics_add_table_project_featuremap() {
  $schema = [
    'fields' => [
      'project_featuremap_id' => ['type' => 'serial', 'not null' => TRUE],
      'project_id' => ['type' => 'int', 'not null' => TRUE],
      'featuremap_id' => ['type' => 'int', 'not null' => TRUE],
    ],
    'primary key' => ['project_featuremap_id'],
    'foreign keys' => [
      'project' => [
        'table' => 'project',
        'columns' => [
          'project_id' => 'project_id',
        ],
      ],
      'featuremap' => [
        'table' => 'featuremap',
        'columns' => [
          'featuremap_id' => 'featuremap_id',
        ],
      ],
    ],
    'indexes' => [
      'project_featuremap_idx1' => ['project_id'],
      'project_featuremap_idx2' => ['featuremap_id'],
    ],
    'unique keys' => [
      'project_featuremap_unique_uq1' => ['project_id', 'featuremap_id'],
    ],
  ];
  chado_create_custom_table('project_featuremap', $schema, TRUE, NULL, FALSE);
}

/**
 * Add custom tables:
 *   stock_analysis, project_featuremap
 */
function carrotomics_add_custom_tables() {
  carrotomics_add_table_stock_analysis();
  carrotomics_add_table_project_featuremap();
}

/**
 * Add three new custom columns to chado.nd_geolocation table
 * to store uncertainty (plus or minus) values
 */
function carrotomics_update_nd_geolocation() {
  db_add_field('chado.nd_geolocation', 'latitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of latitude',
  ]);
  db_add_field('chado.nd_geolocation', 'longitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of longitude',
  ]);
  db_add_field('chado.nd_geolocation', 'altitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of altitude',
  ]);
}

/**
 * Add CV terms used by this module
 */
function carrotomics_add_cv_terms() {
  //
  // Controlled Vocabulary entries
  //
  // The SIO cv does not need to be added because it is
  // automatically added by the base Tripal setup.
  // Add the IAO controlled vocabulary
  chado_insert_cv('IAO', 'Information Artifact Ontology  is a new ontology of information entities, originally driven by work by the OBI digital entity and realizable information entity branch.');
  // Add the EDAM controlled vocabulary
  chado_insert_cv('EDAM', 'EDAM is an ontology of well established, familiar concepts that are prevalent within bioinformatics, including types of data and data identifiers, data formats, operations and topics. EDAM is a simple ontology - essentially a set of terms with synonyms and definitions - organised into an intuitive hierarchy for convenient use by curators, software developers and end-users. EDAM is suitable for large-scale semantic annotations and categorization of diverse bioinformatics resources. EDAM is also suitable for diverse application including for example within workbenches and workflow-management systems, software distributions, and resource registries.');

  //
  // Field types
  //
  $term = chado_insert_cvterm([
    'id' => 'SIO:000013',
    'name' => 'geographic position',
    'cv_name' => 'SIO',
    'definition' => 'A geographic position is the coordinate of an entity against some geographic coordinate system.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'IAO:0000101',
    'name' => 'image',
    'cv_name' => 'IAO',
    'definition' => 'An image is an affine projection to a two dimensional surface, of measurements of some quality of an entity or entities repeated at regular intervals across a spatial range, where the measurements are represented as color and luminosity on the projected on surface.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'data:2091',
    'name' => 'Accession',
    'cv_name' => 'EDAM',
    'definition' => 'A persistent (stable) and unique identifier, typically identifying an object (entry) from a database.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'data:3140',
    'name' => 'Phylogenetic tree',
    'cv_name' => 'EDAM',
    'definition' => 'The raw data (not just an image) from which a phylogenetic tree is directly generated or plotted, such as topology, lengths (in time or in expected amounts of variance) and a confidence interval for each length.',
  ]);

  // local terms
  $term = chado_insert_cvterm([
    'id' => 'local:analysis_project',
    'name' => 'analysis_project',
    'cv_name' => 'local',
    'definition' => 'Used for a Tripal Field to link all projects containing a given analysis',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:biomaterial_project',
    'name' => 'biomaterial_project',
    'cv_name' => 'local',
    'definition' => 'Provides a link from biomaterials to projects or to analyses that use them',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:project_analysis',
    'name' => 'project_analysis',
    'cv_name' => 'local',
    'definition' => 'Used for a Tripal Field to link all analyses within a given project',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:stock_analysis',
    'name' => 'stock_analysis',
    'cv_name' => 'local',
    'definition' => 'Used for a Tripal Field to link all stocks to analyses that use them',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:Number_of_markers',
    'name' => 'Number of markers',
    'cv_name' => 'local',
    'definition' => 'Total number of markers in a linkage map.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:Number_of_quantitative_trait_loci',
    'name' => 'Number of quantitative trait loci',
    'cv_name' => 'local',
    'definition' => 'Total number of quantitative trait loci in a linkage map.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:Number_of_mendelian_trait_loci',
    'name' => 'Number of mendelian trait loci',
    'cv_name' => 'local',
    'definition' => 'Total number of mendelian trait loci in a linkage map.',
  ]);

  $term = chado_insert_cvterm([
    'id' => 'local:Number_of_linkage_groups',
    'name' => 'Number of linkage groups',
    'cv_name' => 'local',
    'definition' => 'Total number of linkage groups in a linkage map.',
  ]);

}

/**
 * Add new project_featuremap table
 */
function carrotomics_update_7100() {
  try {
    carrotomics_add_table_project_featuremap();
  }
  catch (\PDOException $e) {
    $error = $e->getMessage();
    throw new DrupalUpdateException('Could not perform update: '. $error);
  }
}
