<?php
/**
 * @file
 *       Extensions for the CarrotOmics.org site
 *
 * @ingroup carrotomics
 */

//require('theme/carrotomics.theme.inc');
//require('includes/carrotomics.utils.inc');
require_once('api/carrotomics.api.inc');
require_once('includes/carrotomics.fields.inc');
require_once('includes/carrotomics.brapi.inc');
require_once('includes/carrotomics.blast_ui.linkouts.inc');
require_once('includes/admin/carrotomics.admin.inc');
require_once('includes/admin/carrotomics.admin.pub.inc');
require_once('includes/admin/carrotomics.admin.sql.inc');
require_once('includes/admin/carrotomics.admin.validate.inc');
require_once('includes/admin/carrotomics.admin.export.inc');

/**
 * Implements hook_chado_schema_v1_3_table()
 *
 * Purpose: To add descriptions and foreign keys to default table description
 * Note: This array will be merged with the array from all other implementations
 *
 * Here we add three columns to the nd_geolocation table to store uncertainty values
 *
 * @return
 *    Array describing the nd_geolocation table
 *
 * @ingroup tripal_schema_api
 */
function carrotomics_chado_schema_v1_3_nd_geolocation() {

  $description = [
    'fields' => [
      'latitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
      'longitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
      'altitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
    ],
  ];

  return $description;
}

/**
 * Implements hook_chado_schema_v1_3_table()
 *
 * Purpose: To add descriptions and foreign keys to default table description
 * Note: This array will be merged with the array from all other implementations
 *
 * Here we add a unique key constraint to the eimage table because
 * there is none! This prevents using a bulk loader with "insert or update if duplicate" mode.
 * This was added manually with:
 * ALTER TABLE chado.eimage ADD CONSTRAINT eimage_c1 UNIQUE (eimage_data, eimage_type, image_uri);
 *
 * @return
 *    Array describing the nd_geolocation table
 *
 * @ingroup tripal_schema_api
 */
function carrotomics_chado_schema_v1_3_eimage() {

  $description = [
    'unique keys' => [
      'eimage_c1' => [
        0 => 'eimage_data',
        1 => 'eimage_type',
        2 => 'image_uri',
      ],
    ],
  ];

  return $description;
}

/**
 * Implementation of hook_access().
 *
 * Purpose: To restrict access to the CarrotOmics administrative pages
 */
function carrotomics_access($access_args) {
  if (user_access($access_args)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_menu().
 *
 * Purpose: Defines the menu structure for the CarrotOmics administrative pages
 */
function carrotomics_menu() {
  $items = [];

  // Administrative Page Definitions
  $weight = 0;

  $items['admin/carrotomics'] = [
    'title' => 'CarrotOmics',
    'description' => 'Admin page for CarrotOmics',
    'page callback' => 'carrotomics_admin_page',
    'access arguments' => ['admin carrotomics'],
    'access callback' => 'carrotomics_access',
    'file' => '/includes/admin/carrotomics.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => $weight++,
  ];

  $items['admin/carrotomics/validate'] = [
    'title' => 'Validation Functions',
    'description' => 'Functions to find troublesome data',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['carrotomics_admin_validate_form'],
    'access arguments' => ['admin carrotomics'],
    'access callback' => 'carrotomics_access',
    'file' => '/includes/admin/carrotomics.admin.validate.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => $weight++,
  ];

  // we need at least two items for these tabs to show up
  $items['admin/carrotomics/pub'] = [
    'title' => 'Publication Functions',  // note that tab titles display in all upper-case
    'description' => 'Administrative functions for publications',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['carrotomics_admin_pub_form'],
    'access arguments' => ['admin carrotomics'],
    'access callback' => 'carrotomics_access',
    'file' => '/includes/admin/carrotomics.admin.pub.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => $weight++,
  ];

  $items['admin/carrotomics/export'] = [
    'title' => 'Data Export Functions',
    'description' => 'Data export tools',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['carrotomics_admin_export_form'],
    'access arguments' => ['admin carrotomics'],
    'access callback' => 'carrotomics_access',
    'file' => '/includes/admin/carrotomics.admin.export.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => $weight++,
  ];

  $items['admin/carrotomics/sql'] = [
    'title' => 'SQL Functions',
    'description' => 'Custom SQL Functions to modify chado',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['carrotomics_admin_sql_form'],
    'access arguments' => ['admin carrotomics'],
    'access callback' => 'carrotomics_access',
    'file' => '/includes/admin/carrotomics.admin.sql.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => $weight++,
  ];

  return $items;
}
