<?php
/**
 * @file
 *       Extensions for the CarrotOmics.org site
 *
 * @ingroup carrotomics
 */

//require('theme/carrotomics.theme.inc');
//require('includes/carrotomics.utils.inc');
require_once('includes/carrotomics.fields.inc');


/**
 * Implements hook_chado_schema_v1_3_table()
 *
 * Purpose: To add descriptions and foreign keys to default table description
 * Note: This array will be merged with the array from all other implementations
 *
 * Here we add three columns to the nd_geolocation table to store uncertainty values
 *
 * @return
 *    Array describing the nd_geolocation table
 *
 * @ingroup tripal_schema_api
 */
function carrotomics_chado_schema_v1_3_nd_geolocation() {

  $description = [
    'fields' => [
      'latitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
      'longitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
      'altitude_dev' => [
        'size' => 'normal',
        'type' => 'float',
        'not null' => FALSE,
      ],
    ],
  ];

  return $description;
}

/**
 * Implements hook_chado_schema_v1_3_table()
 *
 * Purpose: To add descriptions and foreign keys to default table description
 * Note: This array will be merged with the array from all other implementations
 *
 * Here we add a unique key constraint to the eimage table because
 * there is none! This prevents using a bulk loader with "insert or update if duplicate" mode.
 * This was added manually with:
 * ALTER TABLE chado.eimage ADD CONSTRAINT eimage_c1 UNIQUE (eimage_data, eimage_type, image_uri);
 *
 * @return
 *    Array describing the nd_geolocation table
 *
 * @ingroup tripal_schema_api
 */
function carrotomics_chado_schema_v1_3_eimage() {

  $description = [
    'unique keys' => [
      'eimage_c1' => [
        0 => 'eimage_data',
        1 => 'eimage_type',
        2 => 'image_uri',
      ],
    ],
  ];

  return $description;
}
