<?php

namespace Drupal\carrotomics\Form;

use Drupal\Core\Config\ConfigFactory;
use Drupal\Core\Form\FormStateInterface;
use Drupal\pgsql\Driver\Database\pgsql\Connection;
use Drupal\tripal_chado\Database\ChadoConnection;
use Drupal\tripal\Services\TripalEntityLookup;
use Drupal\tripal\Services\TripalLogger;
use Drupal\tripal\TripalBackendPublish\PluginManager\TripalBackendPublishManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides the user interface for CarrotOmics publication tools.
 */
class CarrotOmicsAdminSql extends CarrotOmicsAdminFormBase {

  /**
   * CarrotOmicsAdminPub class constructor.
   *
   * Prepares injected services.
   */
  public function __construct(
    ConfigFactory $config_factory,
    Connection $drupal_connection,
    ChadoConnection $chado_connection,
    TripalEntityLookup $entity_lookup_manager,
    TripalLogger $logger,
    TripalBackendPublishManager $publish_manager,
  ) {
    parent::__construct($drupal_connection, $chado_connection, $entity_lookup_manager, $logger, $publish_manager);
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('config.factory'),
      $container->get('database'),
      $container->get('tripal_chado.database'),
      $container->get('tripal.tripal_entity.lookup'),
      $container->get('tripal.logger'),
      $container->get('tripal.backend_publish'),
    );
  }

  /**
   * Returns a unique string identifying the form.
   *
   * @return string
   *   The unique string identifying the form.
   */
  public function getFormId() {
    return 'carrotomics_admin_sql_form';
  }

  /**
   * {@inheritdoc}
   *
   * Provides the form definition.
   */
  public function buildForm(array $form, FormStateInterface $form_state) {

    // Attach CSS for stying link buttons.
    $form['#attached']['library'][] = 'carrotomics/carrotomics-admin';

    // An element where submit results will go.
    $storage = $form_state->getStorage();
    if (isset($storage['results'])) {
      $form['pub_results'] = [
        '#type'   => 'fieldset',
        '#title' => 'Results',
        '#markup' => '<div class="form-results">' . $storage['results'] . '</div>',
        '#weight' => -100,
      ];
    }

    // Add a 'Clean MD5 Checksums' button.
    $form['clean_md5_btn'] = [
      '#type'   => 'submit',
      '#name'   => 'clean_md5_btn',
      '#value'  => 'Clean MD5 Checksums',
      '#prefix' => '<div style="padding-top:30px;"><em>'
      . "Remove MD5 checksums of null strings from the feature table, these"
      . " have the value </em>d41d8cd98f00b204e9800998ecf8427e<em>"
      . "</em></div><br />",
      '#suffix' => "<hr>",
    ];

    // ;;;
    if (FALSE) {
      // Add a 'Clean Null taxids' button.
      $form['clean_null_props_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'clean_null_props_btn',
        '#value'  => 'Clean Null properties',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Remove placeholder NULL dbxref entries,"
        . " and NULL entries in the"
        . " stockprop and eimageprop tables"
        . " generated by chado bulk loader"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Populate organism abbreviations' button.
      $form['pop_org_abbrev_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'pop_org_abbrev_btn',
        '#value'  => 'Populate organism abbreviations',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Populate any missing organism abbreviations using"
        . " the chado_get_organism_scientific_name() function"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Populate feature residues Length and Checksum' button.
      $form['residues_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'residues_btn',
        '#value'  => 'Populate feature residues Length and Checksum',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "In the chado.feature table, any record with content in the"
        . " residues column will have the seqlen and md5checksum columns"
        . " populated with appropriate values if they are missing."
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Generate QTL Abbreviations' button.
      $form['qtl_abbrev_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'qtl_abbrev_btn',
        '#value'  => 'Generate QTL Abbreviations',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Generate featureprop entries with MAIN::published_symbol cvterm"
        . " for all QTL lacking them, if they are of the format </em>MK012345 anytext<em>"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Make marker_locus match genetic_marker' button.
      $form['genetic_marker_marker_locus_fix_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'genetic_marker_marker_locus_fix_btn',
        '#value'  => 'Make marker_locus match genetic_marker',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Removes non-alphanumeric or underscore from all features of type genetic_marker,"
        . " and make sure corresponding marker_locus features have the same uniquename"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Generate biomaterial_analysis links' button.
      $form['biomaterial_analysis_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'biomaterial_analysis_btn',
        '#value'  => 'Generate biomaterial_analysis links',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Generate links in the chado.biomaterial_analysis custom table"
        . " using projects common to both"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Generate biomaterial_stock links' button.
      $form['biomaterial_stock_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'biomaterial_stock_btn',
        '#value'  => 'Generate biomaterial_stock links',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Generate links in the chado.biomaterial_stock custom table"
        . " when the stock is present in the biomaterial description"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Generate stock_analysis links' button.
      $form['stock_analysis_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'stock_analysis_btn',
        '#value'  => 'Generate stock_analysis links',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Generate links in the chado.stock_analysis custom table using"
        . " stocks created for phylogenetic trees. Links for both the"
        . " tree analysis and study analysis are made."
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Generate map properties' button.
      $form['map_prop_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'map_prop_btn',
        '#value'  => 'Generate map properties',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Generate chado properties for maps. These are:"
        . " Number of markers,"
        . " Number of linkage groups."
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];
      // Add a 'Assign organisms to phylonodes' button.
      $form['phylo_organism_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'phylo_organism_btn',
        '#value'  => 'Assign organisms to phylonodes',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Phylogenetic tree taxonomic tree leaf nodes will be assigned to"
        . " organisms in the phylotree_organism table if such association"
        . " does not already exist"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

      // Add a 'Transfer from featuremap_stock to stock_featuremap' button.
      $form['featuremap_stock_btn'] = [
        '#type'   => 'submit',
        '#name'   => 'featuremap_stock_btn',
        '#value'  => 'Transfer from featuremap_stock to stock_featuremap',
        '#prefix' => '<div style="padding-top:30px;"><em>'
        . "Move linker records from the mainlab tripal table"
        . " chado.featuremap_stock to the core tripal table"
        . " chado.stock_featuremap"
        . "</em></div><br />",
        '#suffix' => "<hr>",
      ];

    } // ;;;
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {

    $form_state->setRebuild(TRUE);

    // Gets the triggering element, i.e. which button was pressed.
    $triggering_element = $form_state->getTriggeringElement()['#name'];

    // Take action depending on which button was pressed.
    $nerrors = 0;
    $status = '';
    if ($triggering_element == 'clean_md5_btn') {
      [$nerrors, $status] = $this->cleanMd5();
    }
    elseif ($triggering_element == 'clean_null_props_btn') {
      [$nerrors, $status] = carrotomics_admin_clean_null_props();
    }
    elseif ($triggering_element == 'pop_org_abbrev_btn') {
      [$nerrors, $status] = carrotomics_admin_populate_abbreviations();
    }
    elseif ($triggering_element == 'residues_btn') {
      [$nerrors, $status] = carrotomics_admin_residues_length_checksum();
    }
    elseif ($triggering_element == 'qtl_abbrev_btn') {
      [$nerrors, $status] = carrotomics_admin_qtl_abbrev();
    }
    elseif ($triggering_element == 'genetic_marker_marker_locus_fix_btn') {
      [$nerrors, $status] = carrotomics_admin_genetic_marker_marker_locus_fix();
    }
    elseif ($triggering_element == 'biomaterial_analysis_btn') {
      [$nerrors, $status] = carrotomics_admin_biomaterial_analysis_linker();
    }
    elseif ($triggering_element == 'biomaterial_stock_btn') {
      [$nerrors, $status] = carrotomics_admin_biomaterial_stock_linker();
    }
    elseif ($triggering_element == 'stock_analysis_btn') {
      [$nerrors, $status] = carrotomics_admin_stock_analysis_linker();
    }
    elseif ($triggering_element == 'map_prop_btn') {
      [$nerrors, $status] = carrotomics_admin_generate_featuremapprop();
    }
    elseif ($triggering_element == 'phylo_organism_btn') {
      [$nerrors, $status] = carrotomics_admin_phylotree_organism();
    }
    elseif ($triggering_element == 'featuremap_stock_btn') {
      [$nerrors, $status] = carrotomics_admin_featuremap_stock();
    }
    else {
      [$nerrors, $status] = [1, "Unknown button \"$triggering_element\" was pressed"];
    }
    $form_state->setStorage(['results' => $status]);
    if ($nerrors) {
      $this->messenger()->addError($nerrors . ' errors');
    }
  }

  /**
   * Remove MD5 checksums for null strings.
   *
   * Many features get an md5 checksum generated for a null string.
   * These are not useful. This function will remove them.
   */
  protected function cleanMd5() {
    $needs_republishing = [];

    // We need to loop and update each record individually because we
    // need to know the bundle for every record in order to republish.
    $query1 = $this->chado_connection->select('1:feature', 'F');
    $query1->fields('F', ['feature_id']);
    $query1->condition('F.md5checksum', 'd41d8cd98f00b204e9800998ecf8427e', '=');
    $results1 = $query1->execute();

    $count = 0;
    foreach ($results1 as $obj1) {
      $count++;
      $feature_id = $obj1->feature_id;
      $record = $this->getBundleAndEntity('feature', $feature_id);
      if ($record) {
        $bundle = $record[0];
        $needs_republishing[$bundle][$feature_id] = TRUE;
      }
      $query2 = $this->chado_connection->update('1:feature');
      $query2->condition('feature_id', $feature_id, '=');
      $query2->fields(['md5checksum' => NULL]);
      try {
        $query2->execute();
      }
      catch (\Exception $e) {
        $this->logger->error('cleanMd5: exception updating @count md5checksum record: @msg',
          ['@count' => $count, '@msg' => $e->getMessage()]);
        return [1, "Error, exception updating $count md5checksum records: " . $e->getMessage()];
      }
    }

    if ($count) {
      $this->logger->notice('cleanMd5: Updated @count md5checksum records',
        ['@count' => $count]);
      // This will republish if we indicated any updates.
      $this->republish();
      return [0, "Updated $count md5checksum records"];
    }
    else {
      return [0, 'No md5checksum records needed updating'];
    }

  }

}
